repos:
  - repo: local
    hooks:
      - id: ruff-format-check
        name: Ruff Format Check
        entry: uv run ruff check
        language: unsupported
        pass_filenames: false
      - id: isort-check
        name: isort Check
        entry: uv run isort --check .
        language: unsupported
        pass_filenames: false
      - id: ruff-lint
        name: Ruff Lint
        entry: uv run ruff check
        language: unsupported
        pass_filenames: false
      - id: ty-check
        name: Ty Check
        entry: uv run ty check
        language: unsupported
        pass_filenames: false