repos:
  - repo: local
    hooks:
      - id: Cspell-lint
        name: Cspell Lint
        entry: bunx cspell lint
        stages: [manual]
        language: unsupported
        types: [python]
      - id: ruff-format-check
        name: Ruff Format Check
        entry: uv run ruff format --check
        language: unsupported
        types: [python]
      - id: ruff-lint
        name: Ruff Lint
        entry: uv run ruff check
        language: unsupported
        types: [python]
      - id: ty-check
        name: Ty Check
        entry: uv run ty check
        language: unsupported
        types: [python]
