[general]
max_new_tokens = 1024    # (Optional) Maximum number of new tokens to generate, default to 1024
decode_method = "greedy" # (Optional) Decode method for generation, default to "greedy"
streaming = false        # (Optional) Whether to enable streaming output, default to false

[draft]
model_name = "Qwen/Qwen3-0.6B" # (Required) Model name for draft generation
num_draft_tokens = 5           # (Optional) Number of tokens to generate in the draft stage, default to 5

[verify]
model_name = "Qwen/Qwen3-1.7B" # (Required) Model name for verification stage
