[project]
name = "naive-speculate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "VioletsOleander", email = "1377232072@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.12.0",
    "huggingface-hub[cli]>=0.36.0",
    "torch>=2.9.1",
    "transformers>=4.57.1",
]

[project.scripts]
infer = "naive_speculate:main"

[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.1",
    "pytest-repeat>=0.9.4",
]
